### Create user

POST http://localhost:8080/api/users
Content-Type: application/json

{
  "name" : "Carlos",
  "email" : "carloos@gmail.com",
  "role" : "USER",
  "password" : "Barsa123"
}

### Login

POST http://localhost:8080/api/users/me/session
Content-Type: application/json

{
  "email" : "carloos@gmail.com",
  "password" : "Barsa123"
}

### Profile

GET http://localhost:8080/api/users/me
Cookie: session= token.getId();


### Delete
DELETE http://localhost:8080/api/users/me
Cookie: session= token.getId();

### Delete Session
DELETE http://localhost:8080/api/users/me/session
Cookie: session= token.getId(); 